# Generated by Django 3.2.12 on 2023-05-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0008_alter_comment_user_alter_subcomment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='votes',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='votes',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
