# Generated by Django 3.2.12 on 2023-05-25 09:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsapp', '0009_auto_20230525_0606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='votes',
        ),
        migrations.AddField(
            model_name='news',
            name='votes',
            field=models.ManyToManyField(related_name='voted_news', to=settings.AUTH_USER_MODEL),
        ),
    ]
