# Generated by Django 3.2.12 on 2023-05-25 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0012_votes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Votes',
        ),
    ]
