# Generated by Django 3.2.12 on 2023-05-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0014_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='vote',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
