# Generated by Django 3.2.12 on 2023-05-25 11:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsapp', '0015_news_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='vote',
            new_name='votes',
        ),
        migrations.AlterUniqueTogether(
            name='news',
            unique_together={('user', 'id')},
        ),
    ]
