# Generated by Django 3.2.12 on 2023-05-25 12:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsapp', '0016_auto_20230525_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='voted_users',
            field=models.ManyToManyField(blank=True, related_name='voted_news', to=settings.AUTH_USER_MODEL),
        ),
    ]
