# Generated by Django 3.2.12 on 2023-05-26 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0018_delete_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='votes',
        ),
    ]
