# Generated by Django 3.2.12 on 2023-05-29 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsapp', '0024_auto_20230529_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.FileField(blank=True, default=None, null=True, upload_to='comment_img')),
                ('news_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.interacted_news')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.userprofile')),
                ('voted_comment', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
