# Generated by Django 3.2.12 on 2023-05-30 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0025_new_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Subcomment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.FileField(blank=True, default=None, null=True, upload_to='sub_comment_img')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.new_comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.userprofile')),
            ],
        ),
    ]
